version: '3.7'
services:
  db:
      build:
          context: .
          dockerfile: db.Dockerfile
      restart: always
      environment:
          MYSQL_ROOT_PASSWORD: 12345
      volumes:
          - mariadb-data:/var/lib/mysql
      ports:
          - "3306:3306"
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html/
    ports:
      - "8080:80"
    depends_on:
      - db
volumes:
    mariadb-data:
